### ISSUE TITLE
Commands menu

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#18]
I didn't find the "Commands" menu very intuitive; compared to the main buttons it is easy to miss, and it does not feel like the intuitive place to find some of these settings.

I expected to find save / load / restore default settings in the "Settings" command window; and it's not clear why "Random seed" belongs as a "command" rather than a "Simulation" setting.

**Comment by RussellGarwood** [comment]
On the basis of this issue I have:

- Split the menus into a more conventional "File" option (with save/load functions) and a "Commands" option
- Moved the random seed functionality through to the settings menu (good shout on this front - it was only here because of the way I developed the software and it does make very little sense...)
- Made random seed a "proper" simulation variable so it is persistent and saved to settings files
- Updated the documentation to refect these changes

I think this addresses everything above, but if I missed anything, as ever, do shout

**Comment by ms609** [comment]
Looks good; this feels much more intuitive.
Perhaps once the GUI is stable you can update the screen grab images in the documentation pages.
