### ISSUE TITLE
User parameters overwritten when clicking "stochastic layer"

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#20]
To reproduce:
- Open the "Settings→Organisms & Simulation" dialog
- Modify the value of  "Characters for species id / fitness calc"
- Check and uncheck the "Stochastic layer" checkbox

Behaviour:
- The value of  "Characters for species id / fitness calc" is set to its maximum value

Expected behaviour:
- The user's input settings are retained

**Comment by RussellGarwood** [comment]
Ah, this is actually the expected behaviour as the system currently only works with the character number, fitness calculation number, and species ID number being identical - when you select the stochastic option, it updates the other values to match and unenables them. This was, rather, a failure in documentation to mention this, which I have remedied with the above commit!
