### ISSUE TITLE
Setting name of tree output

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#38]
It would be useful to be able to specify the Base name of the Output NEX tree file, or at least to fix it to correspond with the Basename of File One.  Presently, existing output trees will be overwritten during a batch run (though see #35 ), even if the existing trees correspond to a run with different settings and a different File One base name.

**Comment by RussellGarwood** [comment]
If you build following the above commit, there is now a text box allowing you to edit the name of the tree file. This is loaded and saved via the settings file, and otherwise behaves as you would expect based on the other file names. It defaults to the name used before. 

FYI I also took the opportunity to reorganise the dialogue slightly - I have moved the working log file option to the "running log" tab, as it is essentially a highly detailed running log of every operation in the simulation - but it never made it there as it predates the addition of this log.

It just struck me that I will need to modify the documentation to reflect this, and will do so now.

**Comment by RussellGarwood** [comment]
Docs updated with above commit

**Comment by ms609** [comment]
Looks good, a few details to catch:

- [ ] In output settings→End Run Log tab→Tree File, remove the text "The word `tree_` will be appended to the string" – this seems not to be the case, and I think should not be the case
- [ ] Once GUI is stable, images in documentation should be updated
