### ISSUE TITLE
Software paper: References

### ISSUE THREAD

**Issue by ms609** [palaeoware/trevosim#57]
re. openjournals/joss-reviews/issues/6722

Overall, no references are wasted.  

- [x] In "such as birth-death models or randomly generated data", please add a reference to birth-death models, and some sort of reference to help the reader understand what you have in mind by "randomly generated data" (see also #55)

- [x] Optionally, and if there is space, it might add value to the paper if you were to include references that address evolutionary scenarios to those that the new features endeavour to model.  For example, you might pick a couple of interesting case studies to illustrate "scenarios where evolutionary dynamics are driven by variations in the rate of environmental change" (line 121).
A clearer picture of the evolutionary scenarios that TREvoSim v3 can now address might also help to bolster the Statement of Need.

**Comment by RussellGarwood** [comment]
Thanks for these suggestions - I clarified the first point with the above commit (and this has since been further modifed in my changes in light of #55), and I was pleased for the opportunity to add some key references for future directions. Because  the JOSS format encourages a concise reference list, I limited these to the points where I thought they might be most useful (some areas I could potentially have rerefenced are so vast that I didn't really know where to start) - but the additions clearly do help link this to the ideas already out there. Cheers!
